# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852e5f542513ab6cd0f32776a9f5e9b04ead6501f4f2bd4e44e26949a5caa60f76f8ff46956606d8734b2e32ea8dd33de6de0599c2ede3b84c7132d513b18e80

test:
  secret_key_base: 186773aff8b97486f03da8dfdfe35e4d56b7ecab2044c9bc4ef98d9f7d12be11a30484788f5bfc64cc3404d50265a756749f2b00d9bbc0ceeef8f6336d2c20be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
